/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONACCI_H_RPCGEN
#define _FIBONACCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FIBONACCI_PROG 0x23451111
#define FIBONACCI_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FIBONACCI 1
extern  int * fibonacci_1(int *, CLIENT *);
extern  int * fibonacci_1_svc(int *, struct svc_req *);
extern int fibonacci_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIBONACCI 1
extern  int * fibonacci_1();
extern  int * fibonacci_1_svc();
extern int fibonacci_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONACCI_H_RPCGEN */
