/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMOFDIGIT_H_RPCGEN
#define _SUMOFDIGIT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SUMOFDIGIT_PROG 0x12345678
#define SUMOFDIGIT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMOFDIGIT 1
extern  int * sumofdigit_1(int *, CLIENT *);
extern  int * sumofdigit_1_svc(int *, struct svc_req *);
extern int sumofdigit_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMOFDIGIT 1
extern  int * sumofdigit_1();
extern  int * sumofdigit_1_svc();
extern int sumofdigit_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMOFDIGIT_H_RPCGEN */
